version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - .env
    ports:
      - "3306:3306"
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "mysql",
    #       "-h",
    #       "localhost",
    #       "-u",
    #       "root",
    #       "-pksythdud26",
    #       "-e",
    #       "SELECT 1",
    #     ]
    #   timeout: 5s
    #   retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      # db:
      #   # condition: service_healthy
volumes:
  data:
