# Generated by Django 5.0.6 on 2024-07-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
        ('accounts', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
    ]
