# Generated by Django 5.0.6 on 2024-07-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
