# Generated by Django 5.0.6 on 2024-07-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers'),
        ('accounts', '0007_device_token'),
    ]

    operations = [
    ]
