# Generated by Django 5.0.6 on 2024-07-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20240716_0705'),
        ('accounts', '0008_merge_0006_alter_user_managers_0007_device_token'),
    ]

    operations = [
    ]
