# Generated by Django 5.0.6 on 2024-08-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20240719_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
