# Generated by Django 5.0.6 on 2024-09-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20240719_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('html_file', models.FileField(upload_to='patch_note/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
