# Generated by Django 5.0.6 on 2024-09-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_patchnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnote',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
