# Generated by Django 5.0.6 on 2024-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_patchnote_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnote',
            name='email_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patchnote',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
