# Generated by Django 4.2.16 on 2024-11-15 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_social_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('age', models.CharField(blank=True, choices=[('10', 'Ten'), ('20', 'Twenty'), ('30', 'Thirty'), ('40', 'Fourty'), ('50', 'Fifty')], max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('delay_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
