# Generated by Django 4.2.16 on 2024-11-17 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('10', 'Ten'), ('20', 'Twenty'), ('30', 'Thirty'), ('40', 'Fourty'), ('50', 'Fifty')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delay_reason',
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sleep_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wake_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='profile',
            name='delay_reason',
            field=models.ManyToManyField(to='accounts.delayreason'),
        ),
    ]
