# Generated by Django 4.2.16 on 2024-11-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delayreason_remove_profile_user_id_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wake_time',
        ),
    ]
