# Generated by Django 5.0.6 on 2024-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.CharField(max_length=255),
        ),
    ]
