# Generated by Django 5.0.6 on 2024-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='depth',
            field=models.IntegerField(choices=[(1, 'Top Level'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
    ]
