# Generated by Django 5.0.6 on 2024-07-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='depth',
        ),
    ]
