# Generated by Django 5.0.6 on 2024-07-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_category_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtodo',
            name='todo_id',
        ),
        migrations.AddField(
            model_name='subtodo',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtodos', to='todos.todo'),
        ),
    ]
