# Generated by Django 5.0.6 on 2024-07-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_subtodo_todo_alter_todo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.category'),
        ),
    ]
