# Generated by Django 5.0.6 on 2024-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_todo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
