# Generated by Django 5.0.6 on 2024-08-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_subtodo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodo',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todos.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todos.category'),
        ),
    ]
