# Generated by Django 5.0.6 on 2024-08-30 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0010_alter_subtodo_todo_alter_todo_category_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratePrompt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("prompt_content", models.TextField(max_length=255)),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "todo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="todos.todo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvalidContentPrompt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField(max_length=255)),
                (
                    "todo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="todos.todo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuestionPrompt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField(max_length=255)),
                ("answer", models.TextField(max_length=255)),
                (
                    "todo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="todos.todo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
