# Generated by Django 5.0.6 on 2024-09-02 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_generateprompt_invalidcontentprompt_questionprompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvalidContentPrompt',
            new_name='PromptInjection',
        ),
        migrations.RenameModel(
            old_name='QuestionPrompt',
            new_name='PromptQuestion',
        ),
        migrations.RenameField(
            model_name='promptinjection',
            old_name='reason',
            new_name='injection_reason',
        ),
        migrations.CreateModel(
            name='GeneratedSubTodo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('todo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todos.todo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GeneratePrompt',
        ),
    ]
