# Generated by Django 5.0.6 on 2024-10-08 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_userlastusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subtodo',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userlastusage',
            name='last_used_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
