# Generated by Django 4.2.16 on 2024-10-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_rename_todo_subtodo_todo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='subtodo',
            old_name='order',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='order',
            new_name='rank',
        ),
    ]
