# Generated by Django 4.2.16 on 2024-11-05 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_rename_order_category_rank_rename_order_subtodo_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.CharField(default='0|hzzzzz:', max_length=255),
        ),
        migrations.AlterField(
            model_name='subtodo',
            name='rank',
            field=models.CharField(default='0|hzzzzz:', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='rank',
            field=models.CharField(default='0|hzzzzz:', max_length=255),
        ),
    ]
