# Generated by Django 4.2.16 on 2024-10-12 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_alter_category_rank_alter_subtodo_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
