# Generated by Django 4.2.16 on 2024-11-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_alter_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtodo',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='rank',
        ),
        migrations.AddField(
            model_name='subtodo',
            name='ank',
            field=models.CharField(default='0|hzzzzz:', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='ank',
            field=models.CharField(default='0|hzzzzz:', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.CharField(max_length=255),
        ),
    ]
