# Generated by Django 4.2.16 on 2024-11-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_remove_subtodo_rank_remove_todo_rank_subtodo_ank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtodo',
            old_name='ank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='ank',
            new_name='rank',
        ),
    ]
