name: Deploy Django to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
            chmod 600 ec2_key.pem

      - name: Archive code files
        run: |
          mkdir -p archive
          shopt -s extglob
          cp -r !(archive) archive/
          tar -czf my-django-app.tar.gz -C archive .

      - name: Upload code to EC2
        run: |
          INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID }}
          PUBLIC_DNS=${{ secrets.EC2_PUBLIC_DNS }}
          scp -o StrictHostKeyChecking=no -i ec2_key.pem my-django-app.tar.gz ec2-user@$PUBLIC_DNS:~/

      - name: SSH into EC2 and run deployment script
        run: |
          INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID }}
          PUBLIC_DNS=${{ secrets.EC2_PUBLIC_DNS }}
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{secrets.EC2_PUBLIC_DNS}} << 'EOF'
            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
                sudo yum update -y
                sudo yum install -y docker
                sudo service docker start
                sudo usermod -a -G docker ec2-user
            fi
            
            # Pull and run MySQL container
            docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }} -e MYSQL_DATABASE=${{ secrets.DB_NAME }} -e MYSQL_USER=${{ secrets.DB_USER }} -e MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} -p 3306:3306 -d mysql:latest

            # Deploy Django application
            cd ~/my-django-app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            export DJANGO_SETTINGS_MODULE=onestep_be.settings
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PASSWORD=''
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_PORT=${{ secrets.DB_PORT }}
            python manage.py migrate
            sudo systemctl restart my-django-app.service
          EOF
